### ISSUE TITLE
Update URL version parsing to handle non-string entries in p5Versions

### ISSUE THREAD

**Issue by lirenjie95** [processing/p5.js-web-editor#3779]
### p5.js version

2.1.2 and 1.11.11

### What is your operating system?

Windows

### Web browser and version

Firefox 146.0.1(64-bit)

### Actual Behavior

common/p5Versions.js now mixes objects into p5Versions (lines 7-16), but some consumers still assume p5Versions is a string[]; e.g., client/utils/parseURLParams.js uses p5Versions.includes(ver) and then calls v.split('.') inside filter, which will both fail to recognize object-wrapped versions like 2.1.1/1.11.11 and can throw TypeError: v.split is not a function when ?version=1.11 or ?version=1 is provided (since the filter iterates over the objects).

### Expected Behavior

If p5Versions is intended to stay heterogeneous, consider exporting/using a normalized string list for validation and matching in the URL parser (and any similar callers). Suggestion: we can just have a very simple check like this:
```JavaScript
const versions = p5Versions.map((v) => (typeof v === 'string' ? v : v.version));
```

### Steps to reproduce

It was introduced in #3525

**Comment by Shra-05** [comment]
hi,
I’d like to work on this issue if it’s still available.
My understanding is that p5Versions now contains both strings and objects, but some consumers assume it’s a string array and call methods like includes and split, which causes runtime errors.
I plan to normalize p5Versions into a string-only list (using v.version when needed) before validation in the URL parsing logic.
Please let me know if that approach sounds good before I start.

Thanks!

**Comment by lirenjie95** [comment]
> I plan to normalize p5Versions into a string-only list (using v.version when needed) before validation in the URL parsing logic. 

Sounds correct to me. Can you only use string-only list for related functions but keep the original p5Versions array? Thanks!

**Comment by Shra-05** [comment]
Perfect, thanks! 🚀  
I’ll start working on this using a string-only derived list for the relevant URL parsing functions while keeping p5Versions unchanged.

I’ll share a PR shortly. Happy to take the assignment if that helps 🙂

**Comment by lirenjie95** [comment]
@raclim can you please provide any suggestion and assign this task to @Shra-05 ? Thanks!

**Comment by soham555-maker** [comment]
Hi @lirenjie95 and @raclim 👋

I’ve reproduced the issue locally (/?version=1.11, /?version=1) and confirmed the v.split is not a function error occurs due to object entries in p5Versions.

<img width="1918" height="574" alt="Image" src="https://github.com/user-attachments/assets/f65d87f9-1fdb-4f46-b2af-4922b1fdffe4" />

I’ve implemented a fix in 

> client/utils/parseURLParams.js

 by deriving a normalized, string-only list:

```
    const stringP5Versions = p5Versions.map(v =>
      typeof v === 'string' ? v : v.version
    );
    
```

This derived list is then used for validation and matching, while keeping the original p5Versions array unchanged, as suggested.

The fix resolves the crash for:
  - exact versions
  - major.minor (?version=1.11)
<img width="1919" height="544" alt="Image" src="https://github.com/user-attachments/assets/38d48d4f-6839-4f85-a617-8aad8f59f2df" />

  - major only (?version=1)
<img width="1919" height="607" alt="Image" src="https://github.com/user-attachments/assets/861be03e-2389-401f-8eac-cc5b9449526e" />


If this approach looks good, I’d be happy to open a PR. Please feel free to assign the issue to me. Thanks! 🙌

**Comment by soham555-maker** [comment]
Hi everyone! 👋

I apologize for the confusion. I just realized that @Hugo-RM already has 
an active PR ([#3801](https://github.com/processing/p5.js-web-editor/pull/3801)) that fixes this issue, submitted 5 days ago. 

I'm new to open-source contributions and didn't check for existing PRs 
before commenting. My mistake! 

@Hugo-RM - Great work on the fix! I'll review your PR to learn from it.
@raclim @lirenjie95 - Thanks for your patience. I'll look for another 
issue to work on. Any suggestions for good first issues would be appreciated!

Sorry for any noise! 🙏
